### PR TITLE
Resolved Error: Digest method not supported when creating DOGE wallet from CoinKey

### PR DESCRIPTION
**Pull request by creativeJoe007**
Screenshot 2020-10-13 at 16 37 12

### CODE REVIEW

**Comment by junderw** [comment]
Thanks for the catch.

Tests failing because Travis is old. Since this PR doesn't change anything in a meaningful way I'll just merge as is. It is the same way we fixed it in bitcoinjs-lib

https://github.com/bitcoinjs/bitcoinjs-lib/commit/335ed99a1cfae5029948e9f7bd20be8502c74319

**Comment by junderw** [comment]
@jprichardson If we could get a patch version bump and a publish I'd appreciate it.

**Comment by junderw** [comment]
or @vbuterin @MidnightLightning if you have the chance.

**Comment by jprichardson** [comment]
@junderw I have added you to `eckey` and `coinkey` npm packages.

**Pull request merged**
